version: '3.8'

services:
  # 主应用
  warehouse-app:
    build: .
    container_name: warehouse-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql://warehouse_user:warehouse_pass@mysql:3306/warehouse_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - warehouse-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: warehouse-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: warehouse_db
      MYSQL_USER: warehouse_user
      MYSQL_PASSWORD: warehouse_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - warehouse-network

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: warehouse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - warehouse-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: warehouse-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - warehouse-app
    restart: unless-stopped
    networks:
      - warehouse-network

volumes:
  mysql_data:
  redis_data:

networks:
  warehouse-network:
    driver: bridge
